server:
  port: 8080
  servlet:
    context-path: ${CONTEXT_PATH:/bideafactory/book}

management:
  server:
    port: ${MANAGEMENT_PORT:9080}
  endpoints:
    web:
      base-path: /ms-book-service/actuator
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: "ms-book-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"

adapter:
  restconsumer:
    ssl:
      keystore-pass: ${KEY_STORE_PASS}
    timeout: ${CONSUMER_TIMEOUT}
    discount-url: ${DISCOUNT_URL}
  r2dbc:
    database:
      database: ${DB_DATABASE}
      schema: ${DB_SCHEMA}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      host: ${DB_HOST}
      port: ${DB_PORT}

validation:
  schema-filename: book-schema.json
  regex:
    chars: ^([^$<>'\"/\t\n\r&{}]*)$
    date: ^(19[0-9]{2}|2[0-9]{3})-(0[1-9]|1[012])-([123]0|[012][1-9]|31)$

